package resource;

import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Point;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.PrintStream;
import java.net.InetAddress;
import java.net.NetworkInterface;
import java.net.Socket;
import java.net.SocketTimeoutException;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author dmitriz
 */
public class Form extends javax.swing.JFrame {

    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jButton5 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        button1 = new java.awt.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        button2 = new java.awt.Button();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(440, 550));
        setSize(new java.awt.Dimension(430, 470));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                close(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                open(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setName(""); // NOI18N

        jButton1.setText("Отправить");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextArea1KeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTextArea1);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Say_собеседник");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Say, world!"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable1);

        jButton6.setText("меню");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("прикрепить");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel3.setPreferredSize(new java.awt.Dimension(300, 100));

        jLabel6.setFont(new java.awt.Font("Vijaya", 3, 24)); // NOI18N
        jLabel6.setText("Say");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 34, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 580, 410, 490);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/edit.gif"))); // NOI18N
        jButton8.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton8.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton8.setPreferredSize(new java.awt.Dimension(60, 60));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel4.setText("имя:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(770, 100, 120, 140);

        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setDoubleBuffered(false);

        jButton2.setText("Say");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Выход");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Я");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(jList2);

        jButton5.setText("Say, world!");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setText("Say!");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addGap(2, 2, 2)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(499, 90, 270, 350);

        jPanel4.setName(""); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Загрузка...");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(jLabel5)
                .addContainerGap(279, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(10, 10, 440, 490);

        button1.setLabel("Скачать");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jList1);

        button2.setLabel("Загрузить");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        jProgressBar1.setMaximumSize(new java.awt.Dimension(32767, 25));
        jProgressBar1.setMinimumSize(new java.awt.Dimension(10, 25));
        jProgressBar1.setName(""); // NOI18N
        jProgressBar1.setPreferredSize(new java.awt.Dimension(146, 25));
        jProgressBar1.setString("");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(470, 620, 350, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //глобальные переменные проекта "Say!"
    public static String server=null;
    public static resource.msg msg=null;
    public static boolean go=true;
    public static boolean finish=false;
    public static boolean dmitriz_world_in_quit=false;
    public static boolean dmitriz_Say_in_quit=false;
    public static boolean Say_out=false;
    public static ArrayList<Client> clients=new ArrayList<Client>();
    //переменные. отражающие режимы работы приложения
    boolean Say_world=false;
    boolean Say=false;
    boolean I=false;
    Thread dmitriz_world_in;
    Thread dmitriz_Say_in;
    multiimg multiimg=null;
    Thread dmitriz_Say_out;
    //функции проекта
    private boolean ip(String ip) {
        try {
            Socket s=new Socket(ip,17771);
            try {
                Thread.sleep(100);
            } catch(InterruptedException e) {}
            BufferedReader br=new BufferedReader(new InputStreamReader(s.getInputStream()));
            if (br.read()==33) 
            {
                server=ip;
                return true;
            } 
        }   catch(IOException e) {
            return false;
        }     
        return false;
    }
    private void out(){
        msg.setText(jTextArea1.getText());
        msg.setAuthor(Resource.name);
        jTextArea1.removeAll();
        jTextArea1.setText("");
        try{jTextArea1.setCaretPosition(0);}catch(IllegalArgumentException e){}       
        if ((Say_world)&&(((msg.getString()!=null)&&(!msg.getString().equals("")))||(msg.getImage()!=null))) {
            Thread dmitriz_out_world=new Thread(new dmitriz_out_world());
            dmitriz_out_world.start();
        }
        if ((Say)&&(((msg.getString()!=null)&&(!msg.getString().equals("")))||(msg.getImage()!=null))) {
            Say_out=true;
        }
        multiimg=null;
        jLabel3.setIcon(null);
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        out();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void open(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_open
        this.setLocation(500, 50);
        jPanel3.setVisible(false);
        jPanel1.setVisible(false);
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
        try{
                Thread.sleep(11000);
            }catch(InterruptedException e){}
        jTextArea1.setLineWrap(true);     
        //ищем сервер и сохраняем его адрес
        boolean server=false;
        String str="";
        try {
            Enumeration<NetworkInterface> eia=NetworkInterface.getNetworkInterfaces();
            while(eia.hasMoreElements()) {
                Enumeration<InetAddress> inetAddress=eia.nextElement().getInetAddresses();
                while(inetAddress.hasMoreElements()) {
                    InetAddress addr=inetAddress.nextElement();
                    str=addr.getHostAddress();
                    Resource.name=addr.getHostName();
                    try{
                        if (str.substring(0, str.indexOf('.')).equals("192")) 
                    for(int i=str.length()-1;i>0;i--) {
                        if (str.charAt(i)=='.') {
                            str=str.substring(0, i+1);
                            if (ip(str+"1")) {
                                server=true;
                                break;
                            } else break;
                        }
                    }
                        } catch(Exception e){}
                    if (server) break;
                }
                if (server) break;
            }
        }catch(IOException e) {}
        try {
            Socket s=new Socket(Form.server,27776);
            PrintStream ps=new PrintStream(s.getOutputStream());
            ps.println(Resource.name);
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e){}
            ps.close();
            s.close();
        } catch (IOException e){}     
        //
        Thread dmitriz_clients=new Thread(new dmitriz_clients());
        dmitriz_clients.start();
        //
        jPanel1.setLocation(10, 10);
        jPanel2.setLocation(new Point(50,50));
        jPanel2.setVisible(true);
        jPanel3.setLocation(new Point(300,10));   
        jPanel5.setLocation(new Point(35, 30));
        msg=new msg();
    }//GEN-LAST:event_open
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    if (I) {       
        jPanel3.setVisible(false); 
        I=false;
    }
    else{
        jTextField1.setText(Resource.name);
        jTextField1.setEditable(false);
        jPanel3.setVisible(true); 
        I=true;
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        DefaultTableModel model=new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex)
                {
                    return false;
                }
        };
        Vector<String> v=new Vector<String>();
        v.add("Say.message");
        model.setColumnIdentifiers(v);
        model.setRowCount(14);
        resource.Form.jTable1.setModel(model);        
        resource.Form.jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        TableColumn column=resource.Form.jTable1.getColumn(resource.Form.jTable1.getColumnName(0));
        column.setCellRenderer(new resource.MultilineCellRenderer());
        resource.Form.jTable1.setRowHeight(20);
        jPanel2.setVisible(false);
        jPanel1.setVisible(true);
        jLabel1.setText("world");
        jPanel1.setLocation(new Point(5,10));
        Say_world=true;
        dmitriz_world_in_quit=false;
        finish=false;
        dmitriz_world_in=new Thread(new dmitriz_world_in());
        while(!finish){
        try{Thread.sleep(1);}catch(Exception e){}}
        dmitriz_world_in.start();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextArea1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyPressed
        //if (evt.getExtendedKeyCode()==java.awt.event.KeyEvent.VK_ENTER) {
        //    out();                     
        //}
    }//GEN-LAST:event_jTextArea1KeyPressed

    private void close(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_close
        try{
            Socket s=new Socket(server,17772);
            Thread.sleep(100);
            s.close();
        }catch(Exception e){}
        try{
            Socket s=new Socket(server,27774);
            jPanel1.setVisible(false);
            jPanel2.setVisible(true);
            dmitriz_world_in_quit=true;
            s.close();            
        }catch(IOException e){}
    }//GEN-LAST:event_close

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try{
            Socket s=null;           
            dmitriz_world_in_quit=true;
            dmitriz_Say_in_quit=true;
            if (Say_world){
                s=new Socket(server,27774);
                Thread dowland=new Thread(new dowland());
                ObjectInputStream ois=new ObjectInputStream(s.getInputStream());
                try{
                    dowland.start();
                    ois.readObject();
                    resource.dowland.dowland=false;
                    Form.jLabel1.setText("");
                }catch(IOException | ClassNotFoundException e){}
                ois.close();
                s.close();  
                resource.dowland.dowland=false;
            }
            if (Say){
            }
            Say_world=false;
            Say=false;
            jPanel1.setVisible(false);
            jPanel2.setVisible(true);                      
        }catch(IOException e){}
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        JFileChooser selectfile=new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG & GIF Images", "jpg", "gif");
        selectfile.setFileFilter(filter);
        selectfile.showOpenDialog(selectfile);
        Image img=null;
        try {
                img=ImageIO.read(new File(selectfile.getSelectedFile().getPath()));
        }catch(IOException e){}
        if (multiimg==null){
            multiimg=new multiimg(img);
        }
        else{
            multiimg.add(img);
        }
        msg.addImage(multiimg.img);
        jLabel3.setIcon(new ImageIcon(multiimg.img));
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        while(true){
            jTextField1.setText(JOptionPane.showInputDialog("Введите ваше имя"));
            if ((jTextField1.getText()!=null)&&(!jTextField1.getText().equals(""))&&(jTextField1.getText().length()<10)){
                boolean correct=true;
                for (Client client : clients) {
                    if (client.getName().equals(jTextField1.getText())){
                        correct=false;
                        break;
                    }
                }
                if (correct)
                    break;
            }
        }
        Resource.name=jTextField1.getText();
        try {
            Socket s=new Socket(server,27776);
            PrintStream ps=new PrintStream(s.getOutputStream());
            ps.println(Resource.name);
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e){}
            ps.close();
            s.close();
        } catch (IOException e){}       
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
            Socket s=new Socket(server,17772);
            Thread.sleep(100);
            s.close();
        }catch(Exception e){}
        try{
            Socket s=new Socket(server,27774);
            jPanel1.setVisible(false);
            jPanel2.setVisible(true);
            dmitriz_world_in_quit=true;
            s.close();            
        }catch(IOException e){}
        go=false;
        
        this.setDefaultCloseOperation(Form.DISPOSE_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (jList2.getSelectedValue()!=null){
            DefaultTableModel model=new DefaultTableModel();
            Vector<String> v=new Vector<String>();
            v.add("Say.message");
            model.setColumnIdentifiers(v);
            model.setRowCount(14);
            resource.Form.jTable1.setEnabled(false);
            resource.Form.jTable1.setModel(model);
            TableColumn column=resource.Form.jTable1.getColumn(resource.Form.jTable1.getColumnName(0));
            column.setCellRenderer(new resource.MultilineCellRenderer());
            resource.Form.jTable1.setRowHeight(20);
            jPanel2.setVisible(false);
            jPanel1.setVisible(true);
            jPanel1.setLocation(new Point(5,10));
            Say=true;
            dmitriz_Say_in_quit=false;
            finish=false;
            dmitriz_Say_in=new Thread(new dmitriz_Say_in(jList2.getSelectedValue().toString()));
            while(!finish){
            try{Thread.sleep(1);}catch(Exception e){}}
            dmitriz_Say_in.start();  
            dmitriz_Say_out=new Thread(new dmitriz_Say_out(jList2.getSelectedValue().toString()));
            dmitriz_Say_out.start();
            Thread dowland=new Thread(new dowland());
            dowland.start();
        }
        else{
            JOptionPane.showMessageDialog(this, "Вы не выбрали собеседника!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        //процесс интерактивной помощи
        int qwe=0;
    }//GEN-LAST:event_jLabel2MouseClicked
    
    File[] list;
    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        try{
            Socket s=new Socket(server,47771);
            ObjectOutputStream oos=new ObjectOutputStream(s.getOutputStream());
            if (Say_world){
                oos.writeObject("World");
            }
            else{
                String ip_target=null;
                for(Client client: clients){
                    if(client.getName().equals(jLabel1.getText())){
                        ip_target=client.getIp();
                    }
                }
                String ip_me=null;
                Socket ip_of_server=new Socket(server,16661);
                ObjectInputStream ip_stream=new ObjectInputStream(ip_of_server.getInputStream());
                ip_me=(String)ip_stream.readObject();
                oos.writeObject(ip_me+" "+ip_target);
            }
            ObjectInputStream ois=new ObjectInputStream(s.getInputStream());
            list=(File[])ois.readObject();
            DefaultListModel lm=new DefaultListModel();            
            for(File file: list){
                lm.addElement(file.getName());
            }
            jList1.setModel(lm);
            
        }catch(Exception e){}
        jPanel5.setVisible(true);
        jPanel1.setVisible(false);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        Form.jProgressBar1.setValue(100);
        Form.jProgressBar1.setString(Integer.toString(100)+"%");
        FileOutputStream fos=null;
        boolean stream=true;
        try{
            String path;
            JFileChooser selectfile=new JFileChooser();
            int select=selectfile.showOpenDialog(selectfile);
            if(select==0){
                if(selectfile.getSelectedFile().isDirectory()){
                    path=selectfile.getSelectedFile().getName()+"\\"+(String)jList1.getSelectedValue();
                }
                else{
                    path=selectfile.getSelectedFile().getParent()+"\\"+(String)jList1.getSelectedValue();
                }                
                File file=new File(path);
                file.createNewFile();
                file=new File(path);
                fos=new FileOutputStream(file);
                Socket s=new Socket(server,47773);
                ObjectOutputStream oos=new ObjectOutputStream(s.getOutputStream());
                oos.writeObject(list[jList1.getSelectedIndex()]);            
                ObjectInputStream ois=new ObjectInputStream(s.getInputStream());           
                try{
                    s.setSoTimeout(5000);
                    while(true){
                        fos.write((byte[])ois.readObject());
                    }
                }catch(SocketTimeoutException e){}
                ois.close();
                stream=true;
            }   
        }catch(HeadlessException | IOException | ClassNotFoundException e){
            if(stream)
                JOptionPane.showMessageDialog(this, "Ошибка передачи файла");
        }
        try{
            fos.close();
        }catch(Exception e){}
        Form.jProgressBar1.setValue(0);
        Form.jProgressBar1.setString(Integer.toString(0)+"%");
        jPanel5.setVisible(false);
        jPanel1.setVisible(true);
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        Form.jProgressBar1.setValue(100);
        Form.jProgressBar1.setString(Integer.toString(100)+"%");
        boolean file_error=true;
        boolean stream=true;
        try{
            JFileChooser selectfile=new JFileChooser();
            int select=selectfile.showOpenDialog(selectfile);
            File crach=new File(selectfile.getSelectedFile().getName());
            if(select==0){
                File file=selectfile.getSelectedFile();
                crach.createNewFile();
                crach.delete();
                file_error=false;
                String str=null;
                if(Say_world){
                    str="World";
                }            
                else{
                    String ip_target=null;
                    for(Client client: clients){
                        if(client.getName().equals(jLabel1.getText())){
                            ip_target=client.getIp();
                        }
                    }
                    String ip_me=null;
                    Socket ip_of_server=new Socket(server,16661);
                    ObjectInputStream ip_stream=new ObjectInputStream(ip_of_server.getInputStream());
                    ip_me=(String)ip_stream.readObject();
                    Socket directory=new Socket(server,47774);
                    ObjectOutputStream directory_out=new ObjectOutputStream(directory.getOutputStream());
                    str=ip_me+" "+ip_target;
                    directory_out.writeObject(str);
                    ObjectInputStream directory_in=new ObjectInputStream(directory.getInputStream());
                    str=(String)directory_in.readObject();
                }
                FileInputStream fis=new FileInputStream(file);
                Socket s=new Socket(server,47772);
                ObjectOutputStream oos=new ObjectOutputStream(s.getOutputStream());
                oos.writeObject(new File(str+"\\"+file.getName()));
                while(fis.available()>0){
                    byte b[]=new byte[1];
                    fis.read(b);
                    oos.writeObject(b);
                }
                oos.close();
                fis.close();
                stream=false;
            }
        }catch(Exception e){
            if(file_error)
                JOptionPane.showMessageDialog(this, "Ошибка выбора файла");
            if(stream)
                JOptionPane.showMessageDialog(this, "Ошибка передачи файла");
        }
        Form.jProgressBar1.setValue(0);
        Form.jProgressBar1.setString(Integer.toString(0)+"%");
        jPanel5.setVisible(false);
        jPanel1.setVisible(true);
    }//GEN-LAST:event_button2ActionPerformed
    
    boolean window=false;       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    public static javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    public static javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList jList1;
    public static javax.swing.JList jList2;
    public static javax.swing.JPanel jPanel1;
    public static javax.swing.JPanel jPanel2;
    public static javax.swing.JPanel jPanel3;
    public static javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    public static javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public static javax.swing.JTable jTable1;
    public static javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
